/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-03-27 08:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
 String root = request.getContextPath(); 
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(root);
      out.write("/css/style2.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./rMateChartH5.css\"/>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"./rMateChartH5License.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"./rMateGaugeChartH5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./theme.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"./cylinder.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  var interval = setInterval(function () {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type: \"GET\",\r\n");
      out.write("      url: \"http://192.168.0.35:9999/Dispatcher\",\r\n");
      out.write("      dataType: \"json\",\r\n");
      out.write("      success: function(data) {\r\n");
      out.write("        ob = data;\r\n");
      out.write("        \r\n");
      out.write("        var result1 = document.getElementById(\"result1\");\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        result1.innerHTML = \"온도:\"+ob.temp+\",진동 \"+ob.gyro+\",CO \"+ob.smoke+\",불꽃 \"+ob.fire+\", \"+ob.msg;\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"chart1\").setData([parseInt(ob.temp)]);\r\n");
      out.write("        document.getElementById(\"chart2\").setData([parseInt(ob.gyro)]);\r\n");
      out.write("        document.getElementById(\"chart3\").setData([parseInt(ob.smoke)]);\r\n");
      out.write("        document.getElementById(\"chart4\").setData([parseInt(ob.fire)]);\r\n");
      out.write("        console.log(\"온도:\"+ob.temp+\",진동 \"+ob.gyro+\",CO \"+ob.smoke+\",불꽃 \"+ob.fire+\", \"+ob.msg);\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  }, 9900);\r\n");
      out.write("  \r\n");
      out.write("  $(window).on(\"unload\", function(){\r\n");
      out.write("\t    alert(\"call\");\r\n");
      out.write("\t    console.log(\"this will be triggered\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"case\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(root);
      out.write("/img/logo1.png\" alt=\"logo\" class=\"logo\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"sidebar\">\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tsensor log\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tsensor log\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tstreaming\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tHR table\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tlocation info\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menuBtn\">\r\n");
      out.write("\t\t\tfire extinguosher\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<div id=\"content\" style=\"height:520px;\">\r\n");
      out.write("\t\t\t\t<!-- 차트가 삽입될 DIV -->\r\n");
      out.write("\t\t\t\t<div id=\"chartHolder1\" class=\"chartHolder\" style=\"height:130px;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"chartHolder2\" class=\"chartHolder\" style=\"height:130px;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"chartHolder3\" class=\"chartHolder\" style=\"height:130px;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"chartHolder4\" class=\"chartHolder\" style=\"height:130px;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t<div id=\"result1\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"result2\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"result3\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"result4\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input type=\"button\" value=\"종료\" onclick=\"setTimeout()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
